############################################################################
# apps/system/p2recv/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_SYSTEM_P2RECV_PROGNAME)
PRIORITY  = $(CONFIG_SYSTEM_P2RECV_PRIORITY)
STACKSIZE = $(CONFIG_SYSTEM_P2RECV_STACKSIZE)
MODULE    = $(CONFIG_SYSTEM_P2RECV)

MAINSRC = p2recv_main.c

include $(APPDIR)/Application.mk
