############################################################################
# apps/examples/p2touchcal/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME = p2touchcal
PRIORITY = $(CONFIG_EXAMPLES_P2TOUCHCAL_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_P2TOUCHCAL_STACKSIZE)
MODULE = $(CONFIG_EXAMPLES_P2TOUCHCAL)

MAINSRC = p2touchcal.c

include $(APPDIR)/Application.mk
