############################################################################
# apps/examples/p2lvgl/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME = p2lvgl
PRIORITY = $(CONFIG_EXAMPLES_P2LVGL_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_P2LVGL_STACKSIZE)
MODULE = $(CONFIG_EXAMPLES_P2LVGL)

MAINSRC = p2lvgl.c

include $(APPDIR)/Application.mk
