############################################################################
# apps/testing/p2psram/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME = $(CONFIG_TESTING_P2PSRAM_PROGNAME)
PRIORITY = SCHED_PRIORITY_DEFAULT
STACKSIZE = $(CONFIG_TESTING_P2PSRAM_STACKSIZE)
MODULE = $(CONFIG_TESTING_P2PSRAM)

MAINSRC = p2psram_main.c

include $(APPDIR)/Application.mk
