############################################################################
# apps/system/p2help/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME = $(CONFIG_SYSTEM_P2HELP_PROGNAME)
PRIORITY = SCHED_PRIORITY_DEFAULT
STACKSIZE = $(CONFIG_DEFAULT_TASK_STACKSIZE)
MODULE = $(CONFIG_SYSTEM_P2HELP)

MAINSRC = p2help_main.c

include $(APPDIR)/Application.mk
