############################################################################
# apps/system/p2berrybank/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_SYSTEM_P2BERRYBANK_PROGNAME)
PRIORITY  = $(CONFIG_SYSTEM_P2BERRYBANK_PRIORITY)
STACKSIZE = $(CONFIG_SYSTEM_P2BERRYBANK_STACKSIZE)
MODULE    = $(CONFIG_SYSTEM_P2BERRYBANK)

MAINSRC = p2berrybank_main.c

include $(APPDIR)/Application.mk
